### ISSUE TITLE
Refactoring - WebGL

### ISSUE THREAD

**Issue by dev3225** [amosproj/amos2022ws03-software-oscilloscope#125]
## User story
1. As a software developer
2. I need the front end code for WebGL plot be refactored
3. So that it improves readability and reduces complexity

## Acceptance criteria
- [ ]  Improved readability
- [ ]  Reduced usage of Java script for transformed calculations.
- [ ]  Calculations are carried out within WebGL.

## Definition of done (DoD)
- [ ]  Feature/Bug/Change has been implemented
- [ ]  Application compiles successfully
- [ ]  Code is documented

- [ ]  Feature/Bug/Change is tested by at least one unit or e2e test
- [ ]  Tests have been passed without warnings (except "deprecated" warnings)

- [ ]  Changes have been reviewed
- [ ]  PR has been merged to dev branch

- [ ]  New dependencies have been added to bill of materials
- [ ]  Software architecture diagram has been updated
- [ ]  All acceptance criteria are fulfilled
- [ ]  Screenshot is attached to issue

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by jandegen** [comment]
Fixed network traffic bottle neck.
Added debug metrics
Did not fix indicators as they could be migrated to pixi

![Image](https://user-images.githubusercontent.com/81998094/207562659-99dcbc59-1128-41da-9375-9d0d66e4ecd4.png)
