### ISSUE TITLE
Sweep speed min value is to low

### ISSUE THREAD

**Issue by jandegen** [amosproj/amos2022ws03-software-oscilloscope#144]
**Expected Behaviour**
When decreasing the sweep speed the wave update should slow down

**Actual Behaviour**
The wave update is only minimal decreased and more or less not visible

**Comment by nicolaskolbenschlag** [comment]
If you fix this with this issue, #116 is ready, isn't it?

(Might be fixed via changing the step of TimeSweepSliders back to -5 to +5 or so)
