### ISSUE TITLE
Demo day slide

### ISSUE THREAD

**Issue by dev3225** [amosproj/amos2022ws03-software-oscilloscope#189]
## User story
1. As a team member
2.  I need a demo day slide to be created
3. So that, it can be used for the demo day presentation.

## Acceptance criteria
- [x]  Landscape proportions - 16:9
- [x]  File format - PDF
- [x]  File name - demo-day-slide.pdf
- [x]  Contents can be : Project idea, a screenshot, team photo, logo.

## Definition of done (DoD)
- [ ]  Feature/Bug/Change has been implemented
- [ ]  Application compiles successfully
- [ ]  Code is documented

- [ ]  Feature/Bug/Change is tested by at least one unit or e2e test
- [ ]  Tests have been passed without warnings (except "deprecated" warnings)

- [ ]  Changes have been reviewed
- [ ]  PR has been merged to dev branch

- [ ]  New dependencies have been added to bill of materials
- [ ]  Software archticture diagram has been updated
- [ ]  All acceptance criteria are fullfilled
- [ ]  Screenshot is attached to issue

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by jandegen** [comment]
![Image](https://user-images.githubusercontent.com/81998094/216033728-8aff1582-8cee-4e0c-b7a9-e1104482359b.png)



![Image](https://user-images.githubusercontent.com/81998094/216033790-0efc7a02-c35a-4c22-ad41-43199a969bf1.png)
