### ISSUE TITLE
Demo day video

### ISSUE THREAD

**Issue by dev3225** [amosproj/amos2022ws03-software-oscilloscope#190]
## User story
1. As a team member
2. I want a video about the product and its working.
3. So that it can be used for the online demo day 

## Acceptance criteria
- [ ]  File name - 'demo-day-video.mkv' ( any common codec would suffice)
- [ ]  Video length expected - 3 minutes.
- [ ]  Should include a demo of the product.
- [ ]  One slide with requirements and one with design/architecture.

## Definition of done (DoD)
- [ ]  Feature/Bug/Change has been implemented
- [ ]  Application compiles successfully
- [ ]  Code is documented

- [ ]  Feature/Bug/Change is tested by at least one unit or e2e test
- [ ]  Tests have been passed without warnings (except "deprecated" warnings)

- [ ]  Changes have been reviewed
- [ ]  PR has been merged to dev branch

- [ ]  New dependencies have been added to bill of materials
- [ ]  Software archticture diagram has been updated
- [ ]  All acceptance criteria are fullfilled
- [ ]  Screenshot is attached to issue

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by jenswaechtler** [comment]
Should it be a Video of the slides or creating slides? Perhaps we could split it and do two to three (requirement and architecture) issues if slides have to be made.

**Comment by dev3225** [comment]
from the homework planning document what I could understand is that, it should include a small demo of how the software can be used for various processes and one slide each for requirements and architecture. But tbh today's lecture would help us understand may be.
