### ISSUE TITLE
Generator tests

### ISSUE THREAD

**Issue by dev3225** [amosproj/amos2022ws03-software-oscilloscope#192]
## User story
1. As a team member
2. I need the generator to be tested under various test cases
3. So that logic functions as expected.

## Acceptance criteria
- [ ]  All the component and data packaging are working as expected. 
- [ ]  Code coverage of 70+%

## Definition of done (DoD)
- [ ]  Feature/Bug/Change has been implemented
- [ ]  Application compiles successfully
- [ ]  Code is documented

- [ ]  Feature/Bug/Change is tested by at least one unit or e2e test
- [ ]  Tests have been passed without warnings (except "deprecated" warnings)

- [ ]  Changes have been reviewed
- [ ]  PR has been merged to dev branch

- [ ]  New dependencies have been added to bill of materials
- [ ]  Software archticture diagram has been updated
- [ ]  All acceptance criteria are fullfilled
- [ ]  Screenshot is attached to issue

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by jenswaechtler** [comment]
![grafik](https://user-images.githubusercontent.com/13545730/215122234-fbea379e-0bc6-41a8-93f5-a481bdd4b80f.png)

build pipeline now fails if code coverage is under 70%
