### ISSUE TITLE
Performance drop - Time sweep manipulation(current)

### ISSUE THREAD

**Issue by dev3225** [amosproj/amos2022ws03-software-oscilloscope#197]
**Actual behavior**
Adapting the time sweep speed multiple times causes the application to heavily drop performance(Time sweep slider unresponsive, drawing of plot slows down)

**Expected behavior**
Multiple manipulation of time sweep levels should not interfere/affect with the performance of the software.

**Comment by leon-juenemann** [comment]
Latest commit in webgl-minimal PR makes it a lot more performant: https://github.com/amosproj/amos2022ws03-software-oscilloscope/pull/186/commits/e3650bdfa9fd9bfdc3d6ef0b010fbffabfe2f1bb

**Comment by nicolaskolbenschlag** [comment]
When I tested it again, the time sweep performance was not a problem. Maybe we can close this issue today.
