### ISSUE TITLE
Create Team Logo

### ISSUE THREAD

**Issue by jandegen** [amosproj/amos2022ws03-software-oscilloscope#2]
## Task
Create a team logo using the team name "SOSCI"

## Acceptance criteria
- [ ]  Logo uploaded to Deliverables as _sprint-01/team-logo.png_

## Definition of done (DoD)
Not done yet

## DoD general criteria
* Task has been fully implemented
* Task has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by dev3225** [comment]
Team logo successfully decided and agreed upon by all team mates.
