### ISSUE TITLE
Home page - Basic

### ISSUE THREAD

**Issue by sjelodari** [amosproj/amos2022ws03-software-oscilloscope#23]
## User story
1. As a user
2. I want / need a webpage with title and logo

## Acceptance criteria
- [ ] Should include team logo and name.

## Definition of done (DoD)
Not available yet

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by leandertolksdorf** [comment]
![Image](https://user-images.githubusercontent.com/55246283/200821889-4b886322-7993-4041-98da-6dd4a5e00896.png)
