### ISSUE TITLE
Receive signal

### ISSUE THREAD

**Issue by sjelodari** [amosproj/amos2022ws03-software-oscilloscope#24]
## User story
1. As a software developer
2. I want / need the signals sent from generator be received at the front end
3. So that I will be able to use it for visualization.

## Acceptance criteria
- [x] Successfully receiving data sent from generator.

## Definition of done (DoD)
Not available yet

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by jandegen** [comment]
Started working with @PhlppKrmr

**Comment by jandegen** [comment]
**Goal**: Use UDP for data transfer between back- & frontend (frontend is a plain browser application)
**Issue**: There is no way of creating a plain UDP socket directly within the browser. It does not support browser required security concerns.
**Solutions**:
- Switch to websockets over TCP
- Switch to WebRTC protocol
- Create a frontend server (like Node.JS) which handles the back-&frontend communication
