### ISSUE TITLE
Create layout draft for UI

### ISSUE THREAD

**Issue by sjelodari** [amosproj/amos2022ws03-software-oscilloscope#25]
## User story
1. As a user
2. I want a UX optimized layout
3. So that I am able to easily use the application.

## Acceptance criteria
- [x] Cartesian plot should be visible .
- [x] On/Off button. 
- [x] Start/ Stop button for each channel
- [x] Controls for horizontal positioning and time sweep for each channel.
- [x] Format - PDF/PPT/Wireframe

## Definition of done (DoD)
Not available yet

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by sjelodari** [comment]
It should be a simple rectangular where the Cartesian plot is on top left.

**Comment by leandertolksdorf** [comment]
Draft 1 by @leandertolksdorf:
https://www.figma.com/file/FUjBOaoNvWhZBsZoPhYezE/SOSCI?node-id=0%3A3&t=CQ6iNVucbJEArgrq-1
![Oscilloscope](https://user-images.githubusercontent.com/55246283/201995872-c88d97cb-96e5-483f-8a43-4f8a8d112dab.png)
Draft 2 by @jandegen:
![image](https://user-images.githubusercontent.com/55246283/201995945-78622202-dc48-4bdf-81c6-682cda54eb9a.png)
