### ISSUE TITLE
Display cartesian plot

### ISSUE THREAD

**Issue by sjelodari** [amosproj/amos2022ws03-software-oscilloscope#30]
## User story
1. As a user
2. I want a (x, y) cartesian co-ordinate plot 
3. So that I will be able to plot signals from the received signal. 

## Acceptance criteria
- [ ] Proper labeling
- [ ] Plot field manipulatable

## Definition of done (DoD)
Not available yet

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by leandertolksdorf** [comment]
![Image](https://user-images.githubusercontent.com/55246283/200821705-70d0e5ab-4eb4-48c6-8271-55ad9c3ead2c.png)
