### ISSUE TITLE
Setting up CI/CD

### ISSUE THREAD

**Issue by sjelodari** [amosproj/amos2022ws03-software-oscilloscope#40]
## User story
1. As a team member
2. I want a CI/CD pipeline through GitHub Actions
3. So that I can streamline a development or update of product seamlessly.

## Acceptance criteria
- [x] Successful build of code.
- [x] Run unit/acceptance tests automatically and logs errors.
- [x] Packages the code
- [x] Deployment possibility.

## Definition of done (DoD)
Not available yet

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by jandegen** [comment]
Implemented

Succeeded checks in pull requests
![image](https://user-images.githubusercontent.com/81998094/203357634-785dae4a-9a49-4b78-8b43-23a795f9d602.png)

Current dev environment:
![image](https://user-images.githubusercontent.com/81998094/203357791-bae96049-2e23-4c5e-9041-d36885d8a8db.png)
