### ISSUE TITLE
Signal - step function

### ISSUE THREAD

**Issue by dev3225** [amosproj/amos2022ws03-software-oscilloscope#43]
## User story
1. As a software developer
2. I want / need a step function to be generated
3. So that I can view them as a signal through one channel among n channels.

## Acceptance criteria
- [x] Visualization of a step function in cartesian plot.
- [x] No interruption between channels when viewing multiple channels.

## Definition of done (DoD)
Not available yet

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by nicolaskolbenschlag** [comment]
As the features #41, #42 and #43 are so similar (#42 and #43 require one additional line of code on top of #41) that I believed it might make sense to do them altogether. Hence, I moved this feature from the backlog to in progress.
