### ISSUE TITLE
Front end testing procedure

### ISSUE THREAD

**Issue by dev3225** [amosproj/amos2022ws03-software-oscilloscope#47]
## User story
1. As a software developer
2. I need a software testing criteria for front end. 
3. So that all the features are tested properly and errors are found early.
4. I need end to end testing

## Acceptance criteria
- [ ] Accommodates all programming languages used.
- [ ] Tested each feature mentioned in user story.   

## Definition of done (DoD)
Not available yet

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by jenswaechtler** [comment]
![Running tests](https://user-images.githubusercontent.com/13545730/201476008-9be4da7a-7bfd-4431-9f10-5a751cbd3d08.png)

Cypress is up and running. First example tests were added. 
Instructions on how to use it have been added to the README.
