### ISSUE TITLE
Vertical adjustment - Amplitude

### ISSUE THREAD

**Issue by dev3225** [amosproj/amos2022ws03-software-oscilloscope#52]
## User story
1. As a user
2. I want / need an option for vertical adjustment
3. So that I can change the amplification of the signal.

## Acceptance criteria
- [ ] Control UI (Slider) visible clearly.
- [ ] moving left reduces volts per division and moving right increases volts per division.
- [ ] Proper change in amplitude of the signal (eg. volts/division) when user changes.
- [ ] The voltage scale (vertical) should change according to the settings and should be shown to user.

## Definition of done (DoD)
- [ ] Application compiles successfully
- [ ] Code is documented
- [ ] Feature/Bug/Change is tested by at least one unit or e2e test
- [ ] Tests have been passed without warnings (except "deprecated" warnings)
- [ ] Changes have been reviewed
- [ ] PR has been merged to dev branch
- [ ] New dependencies have been added to bill of materials
- [ ] Software architecture diagram has been updated
- [ ] All acceptance criteria are fulfilled
- [ ] Screenshot is attached to issue

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by jenswaechtler** [comment]
The sliders are already implemented in the pr of this [Issue](https://github.com/amosproj/amos2022ws03-software-oscilloscope/issues/61) Does this make the issue obsolete?

**Comment by jenswaechtler** [comment]
@dev3225

**Comment by dev3225** [comment]
Both are different? One is to control the v/div and another one is to move the position of the signal up and down without changing the scale

**Comment by jenswaechtler** [comment]
after starting the application
![image](https://user-images.githubusercontent.com/13545730/204305970-2b5d4f5a-6900-4993-a355-41199c1a1b08.png)
after changing the first and third slider
![image](https://user-images.githubusercontent.com/13545730/204306066-1682c8e4-e988-4974-a5b6-158cada01696.png)
