### ISSUE TITLE
Amplitude indicator  - for each channel

### ISSUE THREAD

**Issue by dev3225** [amosproj/amos2022ws03-software-oscilloscope#53]
## User story
1. As a user
2. I want value indicator on my left side of the plot for the signal.
3. So that I will be able to see the amplitude of the signal being visualized on the cartesian plot.

## Acceptance criteria
- [x]  An amplitude indicator with appropriate dimensions that fits into my UI layout.
- [x]  A zero point should be visible on my plot on the left side.
- [x]  Displays the amplitude of the signal being visualized.
- [x]  Units are appropriately mentioned near the values. 
- [x]  Depending on number of channels number of indicators should vary.
- [x]  Should display both maximum and minimum value of the signal being plotted.
- [x]  Different colors for different channels.

## Definition of done (DoD)

- [ ] Application compiles successfully
- [ ] Code is documented
- [ ] Feature/Bug/Change is tested by at least one unit or e2e test
- [ ] Tests have been passed without warnings (except "deprecated" warnings)
- [ ] Changes have been reviewed
- [ ] PR has been merged to dev branch
- [ ] New dependencies have been added to bill of materials
- [ ] Software architecture diagram has been updated
- [ ] All acceptance criteria are fulfilled
- [ ] Screenshot is attached to issue

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by jandegen** [comment]
![Image](https://user-images.githubusercontent.com/81998094/201345014-aefed136-2c1f-4a37-b6d4-25494d74ad8a.jpg)

Sketch of implementation

**Comment by PhlppKrmr** [comment]
![5B895D8C-B62D-4A89-8445-7F4FAA03EB22](https://user-images.githubusercontent.com/54808295/201354562-c0c5ae14-df7f-4cb9-9851-d9914ecaabf9.jpeg)

Sketch with two channels

**Comment by PhlppKrmr** [comment]
Improved example from Mr. Eckert:
![ranges](https://user-images.githubusercontent.com/54808295/202182107-bd64797d-5d5c-4925-8fae-15d36b7be299.jpg)
