### ISSUE TITLE
Channel colors

### ISSUE THREAD

**Issue by dev3225** [amosproj/amos2022ws03-software-oscilloscope#78]
## User story
1. As a user
2. I need colors specified for each channels 
3. So that the user will not be confused each time the program is fired up.

## Acceptance criteria
- [ ]  Channels : colors = { 1 : Red , 2 : Green , 3 : Blue , 4 : Yellow } 

## Definition of done (DoD)

- [ ] Application compiles successfully
- [ ] Code is documented
- [ ] Feature/Bug/Change is tested by at least one unit or e2e test
- [ ] Tests have been passed without warnings (except "deprecated" warnings)
- [ ] Changes have been reviewed
- [ ] PR has been merged to dev branch
- [ ] New dependencies have been added to bill of materials
- [ ] Software architecture diagram has been updated
- [ ] All acceptance criteria are fulfilled
- [ ] Screenshot is attached to issue

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by leandertolksdorf** [comment]
@dev3225 @sjelodari can be closed, done in #53
